export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER_WALI: "/auth/register-wali",
    REGISTER_ALUMNI: "/auth/register-alumni",
    PROFILE: "/auth/profile",
  },
  DASHBOARD: "/dashboard",
  PPDB: {
    REGISTER: "/ppdb/register",
    LIST: "/ppdb/list",
    VERIFY: (id) => `/ppdb/verify/${id}`,
  },
  SANTRI: {
    LIST: "/santri",
    DETAIL: (id) => `/santri/${id}`,
    CREATE: "/santri",
    UPDATE: (id) => `/santri/${id}`,
    DELETE: (id) => `/santri/${id}`,
    BUKU_INDUK: (id) => `/api/santri/${id}/buku-induk`,
    EXPORT_CSV: "/api/santri/export/csv",
  },
  KELAS: {
    LIST: "/kelas",
    SELECT: "/kelas/select",
    DETAIL: (id) => `/kelas/${id}`,
    CREATE: "/kelas",
    UPDATE: (id) => `/kelas/${id}`,
    DELETE: (id) => `/kelas/${id}`,
    KENAIKAN: "/kelas/action/kenaikan",
    MUTASI: "/kelas/action/mutasi",
  },
  MAPEL: {
    LIST: "/mapel",
    SELECT: "/mapel/select",
    CREATE: "/mapel",
    UPDATE: (id) => `/mapel/${id}`,
    DELETE: (id) => `/mapel/${id}`,
    IMPORT: "/mapel/import",
  },
  NILAI: {
    INPUT: "/nilai",
    SANTRI: (santriId) => `/nilai/santri/${santriId}`,
    PRINT_RAPORT: (santriId) => `/api/nilai/raport/${santriId}/print`,
  },
  TAGIHAN: {
    LIST: "/tagihan",
    WALI: "/tagihan/wali",
    BAYAR: (id) => `/tagihan/${id}/bayar`,
    VERIFIKASI: (id) => `/tagihan/${id}/verifikasi`,
    GENERATE: "/tagihan/generate",
    KUITANSI: (id) => `/api/tagihan/${id}/kuitansi`,
    UPDATE: (id) => `/tagihan/${id}`,
    DELETE: (id) => `/tagihan/${id}`,
  },
  JENIS_TAGIHAN: {
    LIST: "/jenis-tagihan",
    SELECT: "/jenis-tagihan/select",
    CREATE: "/jenis-tagihan",
    UPDATE: (id) => `/jenis-tagihan/${id}`,
    DELETE: (id) => `/jenis-tagihan/${id}`,
  },
  ABSENSI: {
    BULK: "/absensi/bulk",
    CLASS: "/absensi/class",
    WALI: "/absensi/wali",
  },
  PELANGGARAN: {
    LIST: "/pelanggaran",
    WALI: "/pelanggaran/wali",
    CREATE: "/pelanggaran",
    UPDATE: (id) => `/pelanggaran/${id}`,
    DELETE: (id) => `/pelanggaran/${id}`,
  },
  PERIZINAN: {
    LIST: "/perizinan",
    WALI: "/perizinan/wali",
    SUBMIT_WALI: "/perizinan/wali",
    VERIFY: (id) => `/perizinan/${id}/verify`,
    SCAN: "/perizinan/scan",
    QR_CODE: (id, type) => `/api/perizinan/${id}/qr-code/${type}`,
  },
  ALUMNI: {
    LIST: "/alumni",
    CREATE: "/alumni",
    UPDATE: (id) => `/alumni/${id}`,
    DELETE: (id) => `/alumni/${id}`,
    DONASI: "/alumni/donasi",
    VERIFIKASI_DONASI: (id) => `/alumni/donasi/${id}/verifikasi`,
    ACCOUNTS: {
      LIST: "/alumni/accounts",
      CREATE: "/alumni/accounts",
      UPDATE: (id) => `/alumni/accounts/${id}`,
      DELETE: (id) => `/alumni/accounts/${id}`,
    },
  },
  SETTINGS: {
    GET: "/settings",
    SAVE: "/settings",
    PUBLIC: "/settings/public",
  },
  TAHUN_AJARAN: {
    LIST: "/tahun-ajaran",
    CREATE: "/tahun-ajaran",
    ACTIVATE: (id) => `/tahun-ajaran/${id}/activate`,
  },
  PENGUMUMAN: {
    LIST: "/pengumuman",
    ACTIVE: "/pengumuman/active",
    CREATE: "/pengumuman",
    UPDATE: (id) => `/pengumuman/${id}`,
    DELETE: (id) => `/pengumuman/${id}`,
  },
  WALISANTRI: {
    LIST: "/walisantri",
    CREATE: "/walisantri",
    UPDATE: (id) => `/walisantri/${id}`,
    DELETE: (id) => `/walisantri/${id}`,
  }
};
